### ISSUE TITLE
Website not displayed in Firefox 66 - Ubuntu

### ISSUE THREAD

**Issue by Otto-AA** [andreasbm/weightless#39]
When opening the webiste (https://weightless.dev/) I get following error in the console:
`SyntaxError: dynamic module import is not implemented main-9df4cc45.js:1:10916`. A blank webpage is displayed.

Browser: Firefox
Version: 66.0 (64-bit)
OS: Ubuntu 18 LTS

**Comment by andreasbm** [comment]
Thanks for reporting this issue 👍 I just fixed it and deployed a new version of the demo page.
