### ISSUE TITLE
form behavior invalid regex

### ISSUE THREAD

**Issue by rwestlund** [andreasbm/weightless#58]
Using 0.0.34 in Chromium 73.
In my component:
```
import 'weightless/textfield';
// ...
<wl-textfield></wl-textfield>
```
It errors on the first keystroke:
```
Pattern attribute value part => {                  form-element-behavior.js? [sm]:25
  if (value === undefined && part instanceof AttributePart) {
    if (value !== part.value) {
      const name = part.committer.name;
      part.committer.element.removeAttribute(name);
    }
  } else {
    part.setValue(value);
  }
} is not a valid regular expression: Uncaught SyntaxError: Invalid regular expression: /part => {
  if (value === undefined && part instanceof AttributePart) {
    if (value !== part.value) {
      const name = part.committer.name;
      part.committer.element.removeAttribute(name);
    }
  } else {
    part.setValue(value);
  }
}/: Incomplete quantifier
get valid	@	form-element-behavior.js? [sm]:25
refreshAttributes	@	input-behavior.js? [sm]:89
onInput	@	input-behavior.js? [sm]:77
cb	@	event.js? [sm]:6


```

**Comment by brettwillis** [comment]
I've got a very similar problem. 

In the DOM it seems like all the native form elements inside Weightless elements have their attributes set to some huge "function() ..." string, and errors in the console are the same as above post.

E.g. (this is from a minified build):

    <wl-textfield filled="" role="textbox" pristine="" aria-disabled="false" tabindex="0">
        <input id="_5sbs2pd9v2" aria-label="function(e){if(void 0===t&amp;&amp;e instanceof r.a){if(t!==e.value){var n=e.committer.name;e.committer.element.removeAttribute(n)}}else e.setValue(t)}" type="function(e){if(void 0===t&amp;&amp;e instanceof r.a){if(t!==e.value){var n=e.committer.name;e.committer.element.removeAttribute(n)}}else e.setValue(t)}" name="function(e){if(void 0===t&amp;&amp;e instanceof r.a){if(t!==e.value){var n=e.committer.name;e.committer.element.removeAttribute(n)}}else e.setValue(t)}" list="function(e){if(void 0===t&amp;&amp;e instanceof r.a){if(t!==e.value){var n=e.committer.name;e.committer.element.removeAttribute(n)}}else e.setValue(t)}" pattern="function(e){if(void 0===t&amp;&amp;e instanceof r.a){if(t!==e.value){var n=e.committer.name;e.committer.element.removeAttribute(n)}}else e.setValue(t)}" autocomplete="function(e){if(void 0===t&amp;&amp;e instanceof r.a){if(t!==e.value){var n=e.committer.name;e.committer.element.removeAttribute(n)}}else e.setValue(t)}" minlength="function(e){if(void 0===t&amp;&amp;e instanceof r.a){if(t!==e.value){var n=e.committer.name;e.committer.element.removeAttribute(n)}}else e.setValue(t)}" maxlength="function(e){if(void 0===t&amp;&amp;e instanceof r.a){if(t!==e.value){var n=e.committer.name;e.committer.element.removeAttribute(n)}}else e.setValue(t)}" min="function(e){if(void 0===t&amp;&amp;e instanceof r.a){if(t!==e.value){var n=e.committer.name;e.committer.element.removeAttribute(n)}}else e.setValue(t)}" max="function(e){if(void 0===t&amp;&amp;e instanceof r.a){if(t!==e.value){var n=e.committer.name;e.committer.element.removeAttribute(n)}}else e.setValue(t)}" tabindex="0">
    </wl-textfield>

**Comment by brettwillis** [comment]
On Firefox 67.0.1, I get a slightly different message:

    Unable to check <input pattern='function(e){if(void 0===t&&e instanceof r.a){if(t!==e.value){var n=e.committer.name;e.committer.element.removeAttribute(n)}}else e.setValue(t)}'> because the pattern is not a valid regexp: raw brace is not allowed in regular expression with unicode flag

**Comment by PalatinCoder** [comment]
I had the same problem while I was using a mix of weightless and @material/mwc-* components at the same time in the project. The error actually seems to be related to a bug in lit-html. Having the mixture of components led to having multiple versions of lit-html. So for me, removing all @material/mwc-* followed by `rm -rf node_modules && npm i` somehow solved the problem.

**Comment by brettwillis** [comment]
> So for me, removing all @material/mwc-* (replacing them with wl-* components) followed by rm -rf node_modules && npm i somehow solved the problem.

This solved my problem also. Cleaning then re-installing node_modules was the missing step for me.
