### ISSUE TITLE
Features request repository

### ISSUE THREAD

**Issue by eskan** [andreasbm/weightless#66]
Hi Andreas,
i think your stuff we'll be massively used :D. May be to not be flood with feature requests you should think about open an other repository weightless-feature-requests it's a way to keep a clean list of issues until new component are in master.
You can also add an **help wanted** label to the issues to suggest some PRs.
Thanks again for your work,
Cyrille.

**Comment by andreasbm** [comment]
Hi Cyrille!

Thanks a lot for your suggestion! Right now I'm going through the current issues to organize them 👍 For now its manageable and I will keep this repository for feature requests :-) I will have your idea in mind for the future!

Have a great day 🎉
